apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardian-db
  template:
    metadata:
      labels:
        app: guardian-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: guardian_staging
            - name: POSTGRES_USER
              value: guardian
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
