apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-front-config
data:
  APP_ENV: "staging"
  LOG_LEVEL: "debug"
  NODE_ENV: "development"
  AUTH_SERVICE_URL: "http://pm-auth-api:5000"
  IDENTITY_SERVICE_URL: "http://pm-identity-api:5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pm-front
  template:
    metadata:
      labels:
        app: pm-front
    spec:
      containers:
        - name: pm-front
          image: pm-front:latest
          command: ["sh", "-c", "npm install && npm run dev"]
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: pm-front-config
          volumeMounts:
            - name: code
              mountPath: /app
              subPath: .
            - name: node-modules
              mountPath: /app/node_modules
      volumes:
        - name: code
          hostPath:
            path: /mnt/pm-front
            type: Directory
        - name: node-modules
          emptyDir: {}
