apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: identity_staging
            - name: POSTGRES_USER
              value: identity
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/pgdata-identity
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: identity-db
spec:
  type: ClusterIP
  selector:
    app: identity-db
  ports:
    - port: 5432
      targetPort: 5432
